name: CD

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: sbt clean test

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: sbt docker:publish

      - name: Get current version
        id: ver
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
      - name: Assemble fat jar
        run: sbt "set assembly / test := {}; assembly"
      - name: Create GitHub release and attach artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: ${{ contains(steps.ver.outputs.tag, 'rc') }}
          name: Version ${{ steps.ver.outputs.tag }}
          tag_name: ${{ steps.ver.outputs.tag }}
          files: |
            target/scala-2.13/sqs2kinesis-${{ steps.ver.outputs.tag }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
